### ISSUE TITLE
Projectinformatie mbt congestieaanpak toevoegen

### ISSUE THREAD

**Issue by TjeerdSNL** [Netbeheer-Nederland/im-capaciteitskaart#2]
We hebben ook informatie nodig over het project/initiatief dat het probleem in een specifiek congestiegebied gaat oplossen. Deze zie ik niet terug in het model.

**Comment by ritger-alliander** [comment]
Klopt, moet toegevoegd worden. IEC 61968-11 beschrijft een package _Work_, die mogelijk past.

Edit: nieuwe [issue](https://github.com/Netbeheer-Nederland/im-capaciteitskaart/issues/7) geopend.

**Comment by ritger-alliander** [comment]
[Work](https://netbeheer-nederland.github.io/im-capaciteitskaart/Work/) toegevoegd aan informatiemodel.
